name: polyrythms
description: "A study on polyrythms inspired by youtube.com/@project_jdm"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-91.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sound/

flutter_gen:
  output: lib/gen/
  line_length: 120
